### ISSUE TITLE
弹框还是需要能够关闭

### ISSUE THREAD

**Issue by cikichen** [power721/kitty-idea-plugin#5]
毕竟如何老板在旁边，你这关不掉就坑爹了，还有希望提供替换本地图片的方式

**Comment by power721** [comment]
安排！

**Comment by cikichen** [comment]
> 安排！

https://github.com/s-unscrupulous/idea_seat/tree/master/seat/resources/icons ，把这些图片可以加进去

**Comment by cikichen** [comment]
> 安排！

设置了本地图片文件夹没生效，是不是不支持gif

**Comment by power721** [comment]
确实没有考虑gif格式

**Comment by cikichen** [comment]
> 确实没有考虑gif格式

这样没法欣赏鸡你太美了
